version: '3'

services:

  postgresql:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./docker-data/postgresql/postgresql.conf:/etc/postgresql.conf
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sirene


  sirene:
    build: .
    command: /bin/bash
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - postgresql

volumes:
  postgres-data:



