# Generated by Django 2.0.1 on 2018-02-08 03:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('code', models.CharField(help_text='APET700', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='LIBAPET', max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='L4_NORMALISEE', max_length=38)),
                ('commercial_name', models.CharField(help_text='ENSEIGNE', max_length=50)),
                ('creation_date', models.DateField(help_text='DCRET', null=True)),
                ('department', models.CharField(help_text='DEPET', max_length=2)),
                ('is_headquarter', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='NOMEN_LONG', max_length=131)),
                ('siret', models.CharField(db_index=True, help_text='SIREN + NIC', max_length=14, unique=True)),
                ('tel', models.CharField(max_length=10, null=True)),
                ('workforce', models.CharField(help_text='EFETCENT', max_length=6)),
                ('zipcode', models.CharField(help_text='CODPOS', max_length=5)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Created locally')),
                ('is_expired', models.BooleanField(default=False, help_text='Removed from database')),
                ('is_hidden', models.BooleanField(default=False, help_text='Ask to be hidden')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Updated locally')),
                ('last_viewed_filename', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='django_sirene.Activity')),
                ('headquarter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsidiaries', to='django_sirene.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='LegalStatus',
            fields=[
                ('code', models.CharField(help_text='NJ', max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='LIBNJ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('code', models.CharField(help_text='COMET', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='LIBCOM', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='legal_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='django_sirene.LegalStatus'),
        ),
        migrations.AddField(
            model_name='institution',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='django_sirene.Municipality'),
        ),
    ]
