# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-08 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='APET700')),
                ('name', models.CharField(max_length=65, verbose_name='LIBAPET')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=38, verbose_name='L4_NORMALISEE')),
                ('commercial_name', models.CharField(max_length=38, verbose_name='ENSEIGNE')),
                ('creation_date', models.DateField(null=True, verbose_name='DCRET')),
                ('department', models.CharField(max_length=2, verbose_name='DEPET')),
                ('is_headquarter', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=38, verbose_name='NOMENLONG')),
                ('siret', models.CharField(db_index=True, max_length=14, unique=True, verbose_name='SIRENe + NIC')),
                ('tel', models.CharField(max_length=10, null=True)),
                ('workforce', models.CharField(max_length=6, verbose_name='EFETCENT')),
                ('zipcode', models.CharField(max_length=5, verbose_name='CODPOS')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Created locally')),
                ('is_expired', models.BooleanField(default=False, help_text='Removed from database')),
                ('is_hidden', models.BooleanField(default=False, help_text='Ask to be hidden')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Updated locally')),
                ('last_viewed_filename', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='django_sirene.Activity')),
                ('headquarter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiaries', to='django_sirene.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='LegalStatus',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='NJ')),
                ('name', models.CharField(max_length=100, verbose_name='LIBNJ')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='COMET')),
                ('name', models.CharField(max_length=32, verbose_name='LIBCOM')),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='legal_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='django_sirene.LegalStatus'),
        ),
        migrations.AddField(
            model_name='institution',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='django_sirene.Municipality'),
        ),
    ]
