# Generated by Django 2.0.1 on 2018-03-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sirene', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.CharField(help_text='DEPCOMEN', max_length=5, primary_key=True, serialize=False),
        ),
    ]
