# Generated by Django 2.0.1 on 2018-03-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_sirene', '0002_auto_20180301_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='last_viewed_filename',
            new_name='updated_from_filename',
        ),
    ]
